Use dt() instead of not available t()
Otherwise it causes fatal error on upgrade: quad:~# barracuda up-modern

BOA [07:14:55] ==> Skynet Agent v.BOA-2.4.0-dev welcomes you aboard!

BOA [07:14:58] ==> INFO: UPGRADE

Do you want to proceed with the upgrade? [Y/n]

BOA [07:15:04] ==> Aegir on quad.tt.o8.io Debian/wheezy x86_64 PHP 5.6

BOA [07:15:04] ==> INFO: Updating packages sources list...
BOA [07:15:04] ==> INFO: We will use Debian mirror ftp.debian.org
BOA [07:15:11] ==> INFO: Checking BARRACUDA version...
BOA [07:15:11] ==> INFO: BARRACUDA version test: OK
BOA [07:15:11] ==> INFO: Testing repository mirror servers availability...
BOA [07:15:13] ==> INFO: GitHub master repository will be used

BOA [07:15:13] ==> UPGRADE START -> checkpoint:

    * Your e-mail address is notify@omega8.cc
    * Your server hostname is quad.tt.o8.io
    * Your Aegir control panel URL is https://master.quad.tt.o8.io

Do you want to proceed with the upgrade? [Y/n]
BOA [07:15:15] ==> INFO: Cleaning up temp files in /var/opt/
BOA [07:15:15] ==> INFO: Installing extra Drush versions...
BOA [07:15:16] ==> INFO: Drush mini-4-26-08-2014 installation complete
BOA [07:15:17] ==> INFO: Drush mini-6-30-10-2014 installation complete
BOA [07:15:19] ==> INFO: Drush mini-7-17-01-2015 installation complete
BOA [07:15:20] ==> INFO: Running system packages update...
BOA [07:15:46] ==> INFO: Upgrading required libraries and tools...
BOA [07:16:11] ==> INFO: Testing Nginx version...
BOA [07:16:11] ==> INFO: Installed Nginx version nginx/1.7.9, OK
BOA [07:16:11] ==> INFO: Running aptitude full-upgrade...
BOA [07:16:30] ==> INFO: Testing Nginx version...
BOA [07:16:30] ==> INFO: Installed Nginx version nginx/1.7.9, OK
BOA [07:16:30] ==> INFO: Upgrading a few more tools...
BOA [07:16:31] ==> INFO: Checking if PHP upgrade is available
BOA [07:16:34] ==> INFO: PHP EXTRA is --with-ldap --with-gmp --with-xpm-dir=/usr
BOA [07:16:35] ==> INFO: Installed PHP version 5.6.4, OK
BOA [07:16:35] ==> INFO: Installed Redis version 2.8.19, OK
BOA [07:16:40] ==> INFO: Updating MariaDB and PHP configuration
BOA [07:16:40] ==> INFO: Running MySQLTuner check on all databases...
BOA [07:16:40] ==> NOTE! This step may take a LONG time, please wait...
BOA [07:16:41] ==> INFO: OS and services upgrade completed

BOA [07:16:41] ==> INFO: Restarting MariaDB server...
BOA [07:16:54] ==> INFO: Upgrading MariaDB tables if necessary...

Do you want to upgrade Aegir Master Instance? [Y/n]
BOA [07:18:11] ==> INFO: Running Aegir Master Instance upgrade
BOA [07:18:14] ==> INFO: Syncing provision backend db_passwd...
BOA [07:18:17] ==> INFO: Running hosting-dispatch (1/3)...
BOA [07:18:24] ==> INFO: Running hosting-dispatch (2/3)...
BOA [07:18:31] ==> INFO: Running hosting-dispatch (3/3)...
BOA [07:18:31] ==> INFO: Syncing hostmaster frontend db_passwd...
BOA [07:18:41] ==> INFO: Testing previous install...
BOA [07:18:41] ==> INFO: Test OK, we can proceed with Hostmaster upgrade
BOA [07:18:41] ==> INFO: Moving old directories
BOA [07:18:41] ==> INFO: Downloading drush mini-7-17-01-2015...
BOA [07:18:44] ==> INFO: Drush seems to be functioning properly
BOA [07:18:44] ==> INFO: Installing Aegir Provision backend...
BOA [07:18:44] ==> INFO: Downloading Drush and Provision extensions...
BOA [07:18:46] ==> INFO: Running hostmaster-migrate, please wait...
Starting Drush preflight. [0 sec, 2.01 MB]                                                                                          [preflight]
Loading drushrc "/var/aegir/.drush/drushrc.php" into "home.drush" scope. [0.01 sec, 2.02 MB]                                        [bootstrap]
Loading drushrc "/var/aegir/host_master/040/sites/all/drush/drushrc.php" into "drupal" scope. [0.01 sec, 2.03 MB]                   [bootstrap]
Cache HIT cid: 7.0-dev-commandfiles-0-6518c74e952f525cc175ed1519840024 [0.01 sec, 2.38 MB]                                              [debug]

Fatal error: Call to undefined function t() in /var/aegir/.drush/usr/safe_cache_form_clear/safe_cache_form_clear.drush.inc on line 14
Drush command terminated abnormally due to an unrecoverable error.